---
title: "Risk Factors for Leptospirosis"
author: "Yile Shi"
date: '2022-07-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale("LC_ALL", "UK")
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(lme4)
library(DHARMa)
library(pROC)
library(caret)
```

## Exploratory Data Analysis (EDA)

```{r}
# load Leptospirosis data
lep_dat <- readxl::read_excel("Leptospirosis data for MSc SWDS.xlsx")
# fix erroneous data
lep_dat$relationshiphh[lep_dat$relationshiphh == "Son Lnlaw"] = "Son In Law"
lep_dat$gender[lep_dat$relationshiphh %in% c("Wife", "Daughter")] = "Female"
lep_dat$gender[lep_dat$relationshiphh == "Son"] = "Male"
lep_dat$village[lep_dat$village == "village 5"] = "Village 5"
# drop duplicated observations in the dataset
lep_dat <- unique(lep_dat)
```

```{r}
miss_mat <- matrix(nrow = ncol(lep_dat), ncol = 2)
# the number of missing values in each column
miss_mat[, 1] <- apply(lep_dat, 2, function(x) length(x[is.na(x)]))
# the proportion of missing values in each column
miss_mat[, 2] <- round(miss_mat[, 1] / nrow(lep_dat), 4)
row.names(miss_mat) <- colnames(lep_dat)
colnames(miss_mat) <- c("Number", "Proportion")
# keep the columns with missing values
miss_mat <- miss_mat[which(miss_mat[, 1] > 0), ]
# display the matrix in decreasing order
miss_mat[order(miss_mat[, 1], decreasing = TRUE),]
```

```{r}
# drop rows with missing values in age, gender and landuse
lep_dat <- lep_dat %>% drop_na(c(landuse, gender, age))
```

```{r, fig.width = 8, fig.height = 2.5}
# histogram for livestk_home
ggplot(data = lep_dat, aes(x = factor(livestk_home)))+
  geom_bar(stat = "count", width = 0.15, color="darkblue", fill="lightblue") +
  labs(x ="livestk_home")
```

```{r}
# compute the mean distance of each village
dist_mean <- lep_dat %>%
  select(disthosp, village) %>%
  drop_na() %>%
  group_by(village) %>%
  summarize(dist = mean(disthosp))

# impute missing values
for (i in dist_mean$village){
  idx <- which(lep_dat$village == i & is.na(lep_dat$disthosp))
  lep_dat$disthosp[idx] <- dist_mean$dist[which(dist_mean$village == i)]
}
```

```{r, fig.width = 8, fig.height = 4}
# histogram for occupation of people below 18
p1 <- ggplot(data = lep_dat %>% filter(age < 18) %>% drop_na(occupation), 
       aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.25, color="darkblue", fill="lightblue") +
  labs(x ="occupation (age < 18)")

# histogram for occupation of people over 18
p2 <- ggplot(data = lep_dat %>% filter(age >= 18) %>% drop_na(occupation), 
       aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.5, color="darkblue", fill="lightblue") +
  labs(x ="occupation (age >= 18)")

# display
grid.arrange(p1, p2)
```

```{r}
# indices of people below 18 with unrecorded occupation 
idx <- which(lep_dat$age < 18 & is.na(lep_dat$occupation))
# impute with "Student"
lep_dat$occupation[idx] = "Student"
```

```{r, fig.width = 8, fig.height = 6}
# histograms for occupation, conditioning on landuse 
# landuse = riverine
p1 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & landuse == "riverine") %>% 
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.15, color="darkblue", fill="lightblue") +
  labs(x ="riverine")

# landuse = irrigation
p2 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & landuse == "irrigation") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.4, color="darkblue", fill="lightblue") +
  labs(x ="irrigation")

# landuse = pastoral
p3 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & landuse == "pastoral") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.4, color="darkblue", fill="lightblue") +
  labs(x ="pastoral")

# display
grid.arrange(p1, p2, p3)
```
```{r, warning = FALSE}
# chisq test for correlation between occupation and landuse
chisq.test(lep_dat$occupation[lep_dat$age >= 18], 
           lep_dat$landuse[lep_dat$age >= 18])
```

```{r, fig.width = 8, fig.height = 10}
# histograms for occupation, conditioning on gender and constituency
# not displayed in the report

# landuse = pastoral + constituency = Tana North + gender = Male
p1 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Male" & 
                        constituency == "Tana North") %>% 
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.2, color="darkblue", fill="lightblue") +
  labs(x ="Tana North, Male")

# landuse = pastoral + constituency = Tana North + gender = Female
p2 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Female" &
                        constituency == "Tana North") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.08, color="darkblue", fill="lightblue") +
  labs(x ="Tana North, Female")

# landuse = pastoral + constituency = Tana River + gender = Male
p3 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Male" &
                        constituency == "Tana River") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.2, color="darkblue", fill="lightblue") +
  labs(x ="Tana River, Male")

# landuse = pastoral + constituency = Tana North + gender = Female
p4 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Female" &
                        constituency == "Tana River") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.08, color="darkblue", fill="lightblue") +
  labs(x ="Tana River, Female")

# landuse = pastoral + constituency = Ijara + gender = Male
p5 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Male" &
                        constituency == "Ijara") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.15, color="darkblue", fill="lightblue") +
  labs(x ="Ijara, Male")

# landuse = pastoral + constituency = Ijara + gender = Female
p6 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Female" &
                        constituency == "Ijara") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.2, color="darkblue", fill="lightblue") +
  labs(x ="Ijara, Female")

# landuse = pastoral + constituency = Sangailu + gender = Male
p7 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Male" &
                        constituency == "Sangailu") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.3, color="darkblue", fill="lightblue") +
  labs(x ="Sangailu, Male")

# landuse = pastoral + constituency = Sangailu + gender = Female
p8 <- ggplot(data = lep_dat %>% 
               filter(age >= 18 & 
                        landuse == "pastoral" & 
                        gender == "Female" &
                        constituency == "Sangailu") %>%
               drop_na(occupation), 
             aes(x = factor(occupation)))+
  geom_bar(stat = "count", width = 0.2, color="darkblue", fill="lightblue") +
  labs(x ="Sangailu, Female")

grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, ncol = 2)

```

### Feature Selection

```{r}
# drop NAs in occupation, disthosp and location
lep_narm <- lep_dat %>%
  drop_na(occupation, disthosp, location) %>%
  filter(disthosp < 100)
```

```{r}
# count the number of observations in each category in occupation
occ_count <- lep_narm %>% select(occupation, result) %>%
  group_by(occupation) %>%
  count(occupation)

# display in decreasing order
occ_count[order(occ_count$n, decreasing = T),]

# count the number of observations in each category in hhoccup
hhocc_count <- lep_narm %>% select(hhoccup, result) %>%
  group_by(hhoccup) %>%
  count(hhoccup)

# display in decreasing order
hhocc_count[order(hhocc_count$n, decreasing = T),]

```

```{r, fig.width = 8, fig.height = 6}
# not displayed in the report
# stacked bar plot of result, grouped by occupation
p1 <- ggplot(lep_narm, aes(x = occupation, fill = result)) + 
  geom_bar(width = 0.35) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  theme(axis.text.x = element_text(angle = 20, hjust = 1)) +
  labs(x ="occupation")

# stacked bar plot of result, grouped by hhoccup
p2 <- ggplot(lep_narm, aes(x = hhoccup, fill = result)) + 
  geom_bar(width = 0.35) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  theme(axis.text.x = element_text(angle = 20, hjust = 1)) +
  labs(x ="hhoccup")      

# display
grid.arrange(p1, p2)
```

```{r}
# combine categories in `occupation`
lep_narm$occupation[lep_narm$occupation == "Crop Farming"] = "Farmer"
lep_narm$occupation[lep_narm$occupation == "Herdsman"] = "Pastoralist"

# combine categories in `hhoccup`
lep_narm$hhoccup[lep_narm$hhoccup == "Crop Farming"] = "Farmer"
lep_narm$hhoccup[lep_narm$hhoccup == "Herdsman"] = "Pastoralist"
```

```{r}
# drop small groups in occupation and hhoccup 
lep_narm <- lep_narm %>% 
  filter(occupation %in% occ_count$occupation[occ_count$n > 20]) %>%
  filter(hhoccup %in% hhocc_count$hhoccup[hhocc_count$n > 20])
```

```{r, fig.height = 4.5, fig.width = 9}
# stacked barplots result, grouped by levels in factors
# gender
p1 <- ggplot(lep_narm, aes(x = gender, fill = result)) + 
  geom_bar(width = 0.2) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  labs(x ="gender")

# occupation
p2 <- ggplot(lep_narm, aes(x = occupation, fill = result)) + 
  geom_bar(width = 0.35) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  labs(x ="occupation")

# landuse
p3 <- ggplot(lep_narm, aes(x = landuse, fill = result)) + 
  geom_bar(width = 0.3) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  labs(x ="landuse")

# hhoccup
p4 <- ggplot(lep_narm, aes(x = hhoccup, fill = result)) + 
  geom_bar(width = 0.2) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  labs(x ="hhoccup")

p5 <- ggplot(lep_narm, aes(x = hhgender, fill = result)) + 
  geom_bar(width = 0.2) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  labs(x ="hhgender")

# display plots
grid.arrange(p1, p2, p3, p4, p5, ncol = 2)
```

```{r}
prevalence <- function(varname){
  # this function is defined to compute prevalence in different groups
  
  # extract specific variable and result
  subset <- data.frame(lep_narm[, c(varname, "result")])
  # get the levels in the specific variable
  category <- unique(subset[, varname])
  # initialize a data frame to store prevalence
  res <- data.frame(category = category, prevalence = rep(0, length(category)))
  
  # loop to compute prevalence in each level
  for (i in (1 : length(category))){
    # the number of positive observations in level i
    pos <- length(which(subset[, varname] == category[i] & 
                          subset$result == "Positive"))
    # the number of all observations in level i
    total <- length(which(subset[, varname] == category[i]))
    # calculate prevalence, in 4 decimal places
    res$prevalence[i] <-  round(pos / total, 4)
  }
  # display the result
  res
}
```

```{r}
# prevalence in different groups
# gender
prevalence("gender")

# occupation
prevalence("occupation")

# landuse 
prevalence("landuse")

# hhoccup
prevalence("hhoccup")

# hhgender
prevalence("hhgender")
```

```{r, fig.height = 4, fig.width = 9}
# boxplots for continuous variables
# age
p1 <- ggplot(lep_narm, aes(x = result, y = age)) + 
  geom_boxplot(width = 0.25, color = "darkblue", fill = "lightblue") + 
  labs(x = "result")

# altitude
p2 <- ggplot(lep_narm, aes(x = result, y = altitude)) + 
  geom_boxplot(width = 0.25, color = "darkblue", fill = "lightblue") + 
  labs(x = "result")

# nmales
p3 <- ggplot(lep_narm, aes(x = result, y = nmales)) + 
  geom_boxplot(width = 0.25, color = "darkblue", fill = "lightblue") + 
  labs(x = "result")

# nfemales
p4 <- ggplot(lep_narm, aes(x = result, y = nfemales)) + 
  geom_boxplot(width = 0.25, color = "darkblue", fill = "lightblue") + 
  labs(x = "result")

# famsize
p5 <- ggplot(lep_narm, aes(x = result, y = famsize)) + 
  geom_boxplot(width = 0.25, color = "darkblue", fill = "lightblue") + 
  labs(x = "result")

# disthosp
p6 <- ggplot(lep_narm, aes(x = result, y = disthosp)) + 
  geom_boxplot(width = 0.25, color = "darkblue", fill = "lightblue") + 
  labs(x = "result")

# display plots
grid.arrange(p1, p2, p3, p4, p5, p6, ncol = 3)
```

```{r, fig.width = 9, fig.height = 3}
# stacked bar plot of result, grouped by village
ggplot(lep_narm, aes(x = village, fill = result)) + 
  geom_bar() + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x ="village")

# prevalence in each village
prevalence("village")
```

```{r, fig.width = 8, fig.height = 3}
# stacked bar plot of result, grouped by location
ggplot(lep_narm, aes(x = location, fill = result)) + 
  geom_bar() + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x ="location")

# prevalence in each location
prevalence("location")
```

```{r, fig.width = 8, fig.height = 3}
# stacked bar plot of result, grouped by constituency
ggplot(lep_narm, aes(x = constituency, fill = result)) + 
  geom_bar(width = 0.2) + 
  scale_fill_manual(values = c("lightblue", "darkblue")) +
  labs(x ="constituency")

# prevalence in each constituency
prevalence("constituency")
```

## Model Construction and Selection

```{r}
# factorize the response, i.e. result
lep_narm$result <- factor(lep_narm$result)
# initial GLM for binomial response over feature candidates
glm <- glm(result ~ gender + age + occupation + landuse + altitude + 
             famsize + hhoccup + disthosp, 
           data = lep_narm,
           family = binomial(link = "logit"))

# model summary
summary(glm)
# significance check using step()
step(glm, test = "Chisq")
```

```{r}
# GLM with selected variables
glm_selected <- glm(result ~ gender + landuse + hhoccup, 
                  data = lep_narm,
                  family = binomial(link = "logit"))

# model summary
summary(glm_selected)
# significance check
step(glm_selected, test = "Chisq")
```


```{r}
# GLMM with random effect of village on intercept
glmer_v_1 <- glmer(result ~ gender + landuse + hhoccup + (1 | village), 
                   data = lep_narm,
                   family = binomial(link = "logit"))

# model comparison using ANOVA
anova(glmer_v_1, glm_selected)
```
```{r, warning = FALSE}
# GLMMs with village effect and random slopes
# random slope on landuse
glmer_v_2 <- glmer(result ~ gender + landuse + hhoccup + 
                     (1 + landuse| village), 
                 data = lep_narm,
                 family = binomial(link = "logit"))

# random slope on hhoccup
glmer_v_3 <- glmer(result ~ gender + landuse + hhoccup + 
                     (1 + hhoccup| village), 
                 data = lep_narm,
                 family = binomial(link = "logit"))

# model comparison
anova(glmer_v_1, glmer_v_2, glmer_v_3)
```

```{r}
# GLMM with random effect of location on intercept
glmer_l <- glmer(result ~ gender + landuse + hhoccup + (1 | location), 
                 data = lep_narm,
                 family = binomial(link = "logit"))

# model comparison using AIC
AIC(glmer_v_1, glmer_l)
```

### Model Diagnosis

```{r, fig.width = 8, fig.height = 4}
# standard residual plot of the optimal model
plot(glmer_v_1)
```

```{r, fig.width = 8, fig.height = 4}
# simulation in DHARMa package, based on the optimal model
sim <- simulateResiduals(glmer_v_1, 1000)
# scaled residual plot and QQ plot
plot(sim)
```

```{r, warning = FALSE, fig.width = 9, fig.height = 4}
# diagnosis plots for specific explanatory variables
par(mfrow = c(1, 3))
# gender
plotResiduals(sim, form = lep_narm$gender)
# landuse
plotResiduals(sim, form = lep_narm$landuse)
# hhoccup
plotResiduals(sim, form = lep_narm$hhoccup)
```

### Model Evaluation

```{r, fig.width = 8}
# model predictions
# GLMM - village
pred_v_1 <- predict(glmer_v_1, newdata = lep_narm, 
                    re.form = ~(1|village), type = "response")
# GLMM - location
pred_l <- predict(glmer_l, newdata = lep_narm, 
                  re.form = ~(1|location), type = "response")
```

```{r, fig.width = 8}
# ROC and AUC of models
# GLMM - village
roc_v <- roc(lep_narm$result, pred_v_1, ci = TRUE, quiet = TRUE, plot = FALSE)
# GLMM - location
roc_l <- roc(lep_narm$result, pred_l, plot = FALSE, ci = TRUE, quiet = TRUE)
# GLM with selected features
roc_glm <- roc(lep_narm$result, glm_selected$fitted.values, 
               ci = TRUE, quiet = TRUE, plot = FALSE)
```

```{r}
# plot ROC curves using ggplot2
ggroc(list(GLMM_village = roc_v, GLMM_location = roc_l, 
           GLM = roc_glm), size = 1) + 
  geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), 
               color="black", linetype="dashed") 
```

```{r}
# report AUC and 95% CI
data.frame(model = c("glmer_v_1", "glmer_l","glm_selected"), 
           AUC = c(roc_v$auc, roc_l$auc, roc_glm$auc),
           CI.lower = c(roc_v$ci[1], roc_l$ci[1], roc_glm$ci[1]),
           CI.upper = c(roc_v$ci[3], roc_l$ci[3], roc_glm$ci[3]))
```

```{r, include = FALSE}
# cv for mean AUC
# glmer - village
# set random seed
set.seed(1)
# set number of folds and create folds
num_fold <- 10
folds <- createFolds(lep_narm$result, k = num_fold)

# generate training sets and fit regression models
lglep_cv <- NULL
for (i in (1 : num_fold)){
  train_idx <- setdiff(1 : nrow(lep_narm), folds[[i]])
  lglep_cv[[i]] <- glmer(result ~ gender + landuse + hhoccup + (1 | village), 
                         family = "binomial"(link = "logit"), 
                         data = lep_narm, subset = train_idx)
}

# initialize vectors to store predictive values and AUC
pred_v_cv <- NULL
auc_cv <- numeric(num_fold)

# predict and compute AUC of each model 
for (j in (1 : num_fold)){
  # test set
  test_idx <- folds[[j]] 
  # model prediction
  pred_v_cv[[j]] <- data.frame(obs = lep_narm$result[test_idx],
                               pred = predict(lglep_cv[[j]], 
                                              newdata = lep_narm, 
                                              type = "response")[test_idx])
  # compute AUC
  auc_cv[j] <- roc(obs ~ pred, data = pred_v_cv[[j]])$auc
}

meanAUC_v <- round(mean(auc_cv), 4)
```

```{r, include = FALSE}
lglep_cv <- NULL
for (i in (1 : num_fold)){
  train_idx <- setdiff(1 : nrow(lep_narm), folds[[i]])
  lglep_cv[[i]] <- glmer(result ~ gender + landuse + hhoccup + (1|location), 
                         family = "binomial"(link = "logit"), 
                         data = lep_narm, subset = train_idx)
}

# initialize vectors to store predictive values and AUC
pred_v_cv <- NULL
auc_cv <- numeric(num_fold)

# predict and compute AUC of each model 
for (j in (1 : num_fold)){
  # test set
  test_idx <- folds[[j]] 
  # model prediction
  pred_v_cv[[j]] <- data.frame(obs = lep_narm$result[test_idx],
                               pred = predict(lglep_cv[[j]], 
                                              newdata = lep_narm, 
                                              type = "response",
                                              allow.new.levels = T)[test_idx])
  # compute AUC
  auc_cv[j] <- roc(obs ~ pred, data = pred_v_cv[[j]])$auc
}

meanAUC_l <- round(mean(auc_cv), 4)
```

```{r, include = FALSE}
lglep_cv <- NULL
for (i in (1 : num_fold)){
  train_idx <- setdiff(1 : nrow(lep_narm), folds[[i]])
  lglep_cv[[i]] <- glm(result ~ gender + landuse + hhoccup, 
                       family = "binomial"(link = "logit"), 
                       data = lep_narm, subset = train_idx)
}

# initialize vectors to store predictive values and AUC
pred_v_cv <- NULL
auc_cv <- numeric(num_fold)

# predict and compute AUC of each model 
for (j in (1 : num_fold)){
  # test set
  test_idx <- folds[[j]] 
  # model prediction
  pred_v_cv[[j]] <- data.frame(obs = lep_narm$result[test_idx],
                               pred = predict(lglep_cv[[j]], 
                                              newdata = lep_narm, 
                                              type = "response")[test_idx])
  # compute AUC
  auc_cv[j] <- roc(obs ~ pred, data = pred_v_cv[[j]])$auc
}

meanAUC_glm <- round(mean(auc_cv), 4)
```

```{r}
# report the mean AUC across CV
data.frame(model = c("glmer_v_1", "glmer_l","glm_selected"), 
           meanAUC = c(meanAUC_v, meanAUC_l, meanAUC_glm))
```

# Model Interpretation

```{r}
# summary of random intercept model with village effect
summary(glmer_v_1)
```

```{r}
# 95% CI for model parameters
logOR_ci_v <- confint(glmer_v_1, maxpts = 8)
logOR_ci_v
```